baseURL = 'https://www.driescode.dev/blog/'
languageCode = 'en-us'
title = 'dries blog'
theme = 'drixie'

[params]
    mode = "toggle"
    useCDN = false
    subtitle = "A simple blog to share my ideas and thoughts, by *driescode.dev*"
    customcss = [ "css/index.css" ]

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ddries"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/driesddev"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 2

[[menu.main]]
name = "driescode.dev"
url = "https://www.driescode.dev/"
weight = 3